### ISSUE TITLE
fill fields when creating new Tasks via API Procedures

### ISSUE THREAD

**Issue by eliaharm** [creecros/MetaMagik#39]
Hello,
Will it be possible to send values for custom fields when creating new tasks with the provided API procedures?
thanks,

**Comment by creecros** [comment]
I believe so. Never tried, but I don't see why not. You'd have to use: https://docs.kanboard.org/en/latest/api/task_metadata_procedures.html

Let me know.

**Comment by eliaharm** [comment]
Just tried it and it didn't work. even the getTask didn't return the custom fields.

I just need to insert 2 additional field "request_issuer" and "for_department" when creating new tasks (incoming from our help desk) through the API.
Is there a way I can add this option?

**Comment by creecros** [comment]
It's been awhile since I played with api, so I'll need to actually ... study. Yes is the answer. 

I'll play around with it when I get a chance

**Comment by creecros** [comment]
Just tested, works just fine with all the task_metadata_procedures found here: https://docs.kanboard.org/en/latest/api/task_metadata_procedures.html

![image](https://user-images.githubusercontent.com/26339368/56053701-c8c2ed80-5d22-11e9-8841-f7a699b2af04.png)

**Comment by creecros** [comment]
I'm gonna close this since the api procedures work. If you need help still, just let me know. Just keep In mind, meta data is a part of kanboard, so the api procedures also are a part of kanboard. MetaMagik just puts a pretty face on top of that existing functionality, and adds a few tools to go with it to make it easier to utilize as custom fields.

**Comment by eliaharm** [comment]
ok, thanks for the help.
