### ISSUE TITLE
Updating a field in task view doesn't fire up a Webhook

### ISSUE THREAD

**Issue by Markus-** [creecros/MetaMagik#63]
Hi,

I created a Meta-Field which I update in the Project->Task-View.
There is no Webhook event when I save the change.

Is this working as designed?
Could this be adjusted?

Regards
markus

**Comment by creecros** [comment]
I didn't ever use web hooks to notice. I'm sure it can be added, not sure if its something I'll get around to do any time soon.

**Comment by Markus-** [comment]
I am not sure if you have to add it. I just added another meta data field from the task view (not MetaMagik) and there is also no update. Will ask in the forum...

Regards
Markus

**Comment by creecros** [comment]
does it trigger if you simply update a normal field?

**Comment by Markus-** [comment]
Yes. If I Update the priority or other stuff the webhook is triggered.
If I update or add a metadata-field it is not.

**Comment by creecros** [comment]
so, most likely the task models trigger the events, and the metadata model doesn't even bother including them. makes sense imo, since metadata is really behind the scenes. so, this would pose a question, if implemented. would it be appropriate to trigger the events for any metadata update, or just custom fields?

again, I have no idea when or if I would ever get around to this. but something to think about.

**Comment by Markus-** [comment]
Let's close this and come up with it again if it is necessary.

Regards
Markus
