### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by samjunction** [creecros/MetaMagik#71]
Please add support for date time field

**Comment by creecros** [comment]
not sure when I can get around to it, but in the meantime, just change the input type of `date` to `datetime-local` in the helper file, line 47. that should do it. if it has no effect, try restarting your server before you make that determination.

**Comment by samjunction** [comment]
Hi,

It worked fine.

Thanks a lot.

Sandeep.

**Comment by samjunction** [comment]
Hi,

How to detect field type in meta_footers.php ? For example i want to apply
date/time formatting to custom field of type date or date/time

Thanks,
Sandeep

**Comment by samjunction** [comment]
Hi,

Please ignore. I found it. I was not looking it carefully.

Sandeep.

**Comment by samjunction** [comment]
Hi,

I can use $custom_field['data_type'] to identify field type but not sure
how to apply date/time formatting. I am not familiar with php.

Sandeep.

**Comment by creecros** [comment]
can you be specific, what do you mean by formatting? what are you trying to do?

**Comment by creecros** [comment]
actually I think I follow you. 

I literally have no server to even test and look at things right now, so I can only guess here.

you seem to have successfully changed the input to date/time. now, you want the footer to show date/time? my guess is, it works on new things you have input, but not old fields when you had just date? if thats the case, the reason would be, because that information (time) was not stored in the database previously. if you update the value,  it should now have that information to display. or, you would have to check the data, and if time isn't included in the stored value, display a generic time, like 00:00. The later could get complicated for you. I'm just guessing here. maybe you are trying to achieve something else.

**Comment by samjunction** [comment]
Hi,

I want to display custom field value of datatype date in mm/dd/yyyy
hour:minute am/pm format.


Sandeep

**Comment by creecros** [comment]
can you screen shot what it currently shows

**Comment by samjunction** [comment]
Hi,

See attached screenshots. I managed to change the date/time format.

Sandeep.
